name: Code style

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  code-style:
    name: Code style
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        php-version:
          - 8.0

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ matrix.php-version }}
          tools: cs2pr
          extensions: ssh2

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v1
        with:
          dependency-versions: lowest
          composer-options: "--prefer-stable"

      - name: Run php-cs-fixer
        run: vendor/bin/php-cs-fixer fix --dry-run --format=checkstyle | cs2pr
