name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: PHPCS Code Review
        uses: rtCamp/action-phpcs-code-review@v2.0.4
        env:
          GH_BOT_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
          SKIP_FOLDERS: "tests,.github"
