name: Static analysis

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  static-analysis:
    name: Static analysis with PHP ${{ matrix.php-version }}
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        php-version: ['8.0']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ matrix.php-version }}
          tools: cs2pr
          extensions: ssh2

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v1
        with:
          dependency-versions: lowest
          composer-options: '--prefer-stable'

      - name: Run phpstan
        run: vendor/bin/phpstan analyse --error-format=checkstyle | cs2pr
